#!/usr/bin/env bash

s=${1:-"s"}
x=${2:-"x"}
command=${3:-"npm run web -s"}

chokidar \
	'package.json' \
	'$s/**/*.css' \
	'$x/**/*.html.js' \
	'$x/**/*.turtle.js' \
	'$x/**/*.context.js' \
	-c '$command && echo rebuilt web';

