#!/usr/bin/env bash

dir="$(dirname $0)"
s=${1:-"s"}
x=${2:-"x"}
in=${3:-"s:x"}
exclude=${4:-"**/*.partial.html.js"}

chokidar \
	"package.json" \
	"$s/**/*.css" \
	"$x/**/*.html.js" \
	"$x/**/*.turtle.js" \
	"$x/**/*.context.js" \
	-c "$dir/turtle-web '$in' '$x' '$exclude'";

