#!/usr/bin/env bash

dir="$(dirname $0)"
in=${1:-"s:x"}
out=${2:-"x"}
exclude=${3:-"**/*.partial.html.js:**/*.map"}

chokidar \
	"package.json" \
	"s/**/*.css" \
	"x/**/*.html.js" \
	"x/**/*.turtle.js" \
	"x/**/*.context.js" \
	-c "$dir/turtle-web '$in' '$out' '$exclude'";

