#!/usr/bin/env bash

s=${1:-"s"}
x=${2:-"x"}
main=${3:-"main.js"}

rm -rf $x && mkdir -p $x
importly --host=node_modules < package-lock.json > $x/importmap.json

ln -s $(realpath $s) $x/$s
ln -s $(realpath node_modules) $x/node_modules

tsc
"$(dirname $0)/turtle-bundle" $x/$main

