#!/usr/bin/env bash

npm i es-module-shims@latest;

npm i --save-dev \
	http-server@latest \
	typescript@latest \
	importly@latest \
	rollup@latest \
	@rollup/plugin-node-resolve@latest \
	terser@latest \
	chokidar@latest \
	chokidar-cli@latest;

